name: CI

on:
  push:
  pull_request:

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config dpkg-dev

      - name: Build deb package
        run: |
          make clean
          make deb

      - name: Upload deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubsh-deb
          path: |
            kubsh_*.deb
            kubsh.deb

  tests:
    runs-on: ubuntu-latest
    needs: build-deb

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config docker.io

      - name: Build binary
        run: |
          make clean
          make build
          ls -l kubsh

      - name: Run official tests
        run: |
          docker pull tyvik/kubsh_test:master
          docker run --rm -v "$(pwd)/kubsh:/usr/local/bin/kubsh" tyvik/kubsh_test:master /opt/check.sh